version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'hammeredkitchendev'
      POSTGRES_PASSWORD: 'moarPizza'
      POSTGRES_DB: 'kitchen-organizer'
    ports:
      - '5432:5432'
volumes:
  postgres_data:
